# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "America/Kentucky/Louisville"
    commit-message:
      prefix: "gradle"

